FROM python:3.11
WORKDIR /app
COPY ./requirements_api.txt /app/requirements_api.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements_api.txt
COPY ./main.py /app/main.py
COPY ./autoencoder_dns.keras /app/autoencoder_dns.keras
COPY ./scaler_dns.pkl /app/scaler_dns.pkl
COPY ./threshold.pkl /app/threshold.pkl
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]
